-- MySQL Script generated by MySQL Workbench
-- Sat Feb  4 11:13:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema databasetest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema databasetest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `databasetest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `databasetest` ;

-- -----------------------------------------------------
-- Table `databasetest`.`ns_dschucvu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasetest`.`ns_dschucvu` (
  `ChucVuID` INT NOT NULL,
  `TenChucVu` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`ChucVuID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `databasetest`.`ns_dsloaihopdong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasetest`.`ns_dsloaihopdong` (
  `LoaiHopDongID` INT NOT NULL,
  `TenLoaiHopDong` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`LoaiHopDongID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `databasetest`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasetest`.`nhanvien` (
  `NhanVienID` INT NOT NULL,
  `MaNhanVien` VARCHAR(20) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `HoVaTen` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `NgaySinh` DATETIME NULL DEFAULT NULL,
  `GioiTinh` VARCHAR(20) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `QueQuan` VARCHAR(500) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `PhongBanID` INT NULL DEFAULT NULL,
  `ChucVuID` INT NULL DEFAULT NULL,
  `LoaiHopDongID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`NhanVienID`),
  INDEX `PhongBanID` (`PhongBanID` ASC) VISIBLE,
  INDEX `ChucVuID` (`ChucVuID` ASC) VISIBLE,
  INDEX `LoaiHopDongID` (`LoaiHopDongID` ASC) VISIBLE,
  CONSTRAINT `nhanvien_ibfk_2`
    FOREIGN KEY (`ChucVuID`)
    REFERENCES `databasetest`.`ns_dschucvu` (`ChucVuID`),
  CONSTRAINT `nhanvien_ibfk_3`
    FOREIGN KEY (`LoaiHopDongID`)
    REFERENCES `databasetest`.`ns_dsloaihopdong` (`LoaiHopDongID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `databasetest`.`ns_hopdong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasetest`.`ns_hopdong` (
  `HopDongID` INT NOT NULL,
  `MaHopDong` VARCHAR(20) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `NhanVienID` INT NULL DEFAULT NULL,
  `LoaiHopDongID` INT NULL DEFAULT NULL,
  `NgayKyHD` DATETIME NULL DEFAULT NULL,
  `NgayBatDau` DATETIME NULL DEFAULT NULL,
  `NgayKetThuc` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`HopDongID`),
  INDEX `NhanVienID` (`NhanVienID` ASC) VISIBLE,
  INDEX `LoaiHopDongID` (`LoaiHopDongID` ASC) VISIBLE,
  CONSTRAINT `ns_hopdong_ibfk_1`
    FOREIGN KEY (`NhanVienID`)
    REFERENCES `databasetest`.`nhanvien` (`NhanVienID`),
  CONSTRAINT `ns_hopdong_ibfk_2`
    FOREIGN KEY (`LoaiHopDongID`)
    REFERENCES `databasetest`.`ns_dsloaihopdong` (`LoaiHopDongID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `databasetest`.`phongban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `databasetest`.`phongban` (
  `PhongBanID` INT NOT NULL,
  `MaPhongBan` VARCHAR(20) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `TenPhongBan` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`PhongBanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
